#!/bin/sh

WORKSPACE=$PWD
STORYBOOK_PATH=$WORKSPACE/$INPUT_STORYBOOK_PATH

export CI_BUILD_ID=$GITHUB_RUN_ID
export LOST_PIXEL_URL=$INPUT_LOST_PIXEL_URL
export LOST_PIXEL_API_KEY=$INPUT_LOST_PIXEL_API_KEY
export LOST_PIXEL_PROJECT_ID=$INPUT_LOST_PIXEL_PROJECT_ID
export STORYBOOK_PATH=$INPUT_STORYBOOK_PATH
export S3_END_POINT=$INPUT_S3_END_POINT
export S3_ACCESS_KEY=$INPUT_S3_ACCESS_KEY
export S3_SECRET_KEY=$INPUT_S3_SECRET_KEY
export S3_BUCKET_NAME=$INPUT_S3_BUCKET_NAME
export S3_BASE_URL=$INPUT_S3_BASE_URL
export IMAGE_PATH_REFERENCE=$WORKSPACE/.loki/reference
export IMAGE_PATH_CURRENT=$WORKSPACE/.loki/current
export IMAGE_PATH_DIFFERENCE=$WORKSPACE/.loki/difference

echo "WORKSPACE=$WORKSPACE"
echo "STORYBOOK_PATH=$STORYBOOK_PATH"
echo "CI_BUILD_ID=$CI_BUILD_ID"
echo "LOST_PIXEL_URL=$LOST_PIXEL_URL"
echo "LOST_PIXEL_API_KEY=$LOST_PIXEL_API_KEY"
echo "LOST_PIXEL_PROJECT_ID=$LOST_PIXEL_PROJECT_ID"
echo "STORYBOOK_PATH=$STORYBOOK_PATH"
echo "S3_END_POINT=$S3_END_POINT"
echo "S3_ACCESS_KEY=*****************"
echo "S3_SECRET_KEY=*****************"
echo "S3_BUCKET_NAME=$S3_BUCKET_NAME"
echo "S3_BASE_URL=$S3_BASE_URL"
echo "IMAGE_PATH_REFERENCE=$IMAGE_PATH_REFERENCE"
echo "IMAGE_PATH_CURRENT=$IMAGE_PATH_CURRENT"
echo "IMAGE_PATH_DIFFERENCE=$IMAGE_PATH_DIFFERENCE"

cd /app

./node_modules/.bin/loki \
--verboseRenderer \
--requireReference \
--reactUri file:$STORYBOOK_PATH \
--reference $WORKSPACE/.loki/reference \
--output $WORKSPACE/.loki/current \
--difference $WORKSPACE/.loki/difference \
--chromeFlags="--headless --disable-gpu --hide-scrollbars --no-sandbox" \
test

npm run start
